server:
  servlet:
    context-path: /
  ssl:
    enabled: false
  port: 8086
spring:
  datasource:
    url: "jdbc:mysql://db-6t4fg.pub-cdb.ntruss.com/eardb?serverTimezone=UTC&characterEncoding=UTF-8"
    username: "sullivan_db"
    password: "sullivan2w3e4r!"
    driver-class-name: "com.mysql.cj.jdbc.Driver"

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true

  redis:
    host: localhost
    password: password
    port: 6379

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE