spring:  profiles:    active:    - prod   # - dev  datasource:    url: "jdbc:mysql://db-6t4fg.pub-cdb.ntruss.com/eardb?serverTimezone=UTC&characterEncoding=UTF-8"    username: "sullivan_db"    password: "sullivan2w3e4r!"
    driver-class-name: "com.mysql.cj.jdbc.Driver"  session:
    store-type: "none"  jpa:    database: "mysql"
    database-platform: "org.hibernate.dialect.MySQL5InnoDBDialect"
    show-sql: true
    open-in-view: false